spring:
  datasource:
    url: jdbc:postgresql://integration-db:5432/integration_db
    username: ${DB_USERNAME:integration_user}
    password: ${DB_PASSWORD:integration_pass}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Integration Configuration
integration:
  laravel:
    base-url: ${LARAVEL_BASE_URL:http://laravel-app:8000}
    api-token: ${LARAVEL_API_TOKEN:dummy-token}
  
  sync:
    employee:
      enabled: true
      # Timer-based scheduling: delay=60s, period=2h (7200s)
      delay: 60000
      period: 7200000
      batch-size: 100
    payroll:
      enabled: true
      # Timer-based scheduling: delay=120s, period=3h (10800s)
      delay: 120000
      period: 10800000
      batch-size: 50
    accounting:
      enabled: true
      # Timer-based scheduling: delay=180s, period=4h (14400s)
      delay: 180000
      period: 14400000
      batch-size: 50

# ERP Configuration
erp:
  frappe:
    enabled: ${ERP_FRAPPE_ENABLED:false}
    base-url: ${ERP_FRAPPE_URL:}
    api-key: ${ERP_FRAPPE_API_KEY:}
    api-secret: ${ERP_FRAPPE_API_SECRET:}
  generic:
    enabled: ${ERP_GENERIC_ENABLED:false}
    base-url: ${ERP_GENERIC_URL:}
    username: ${ERP_GENERIC_USERNAME:}
    password: ${ERP_GENERIC_PASSWORD:}

logging:
  level:
    com.hrboilerplate.integration: DEBUG
    org.apache.camel: INFO