services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel_boilerplate
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    networks:
      - laravel

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel_boilerplate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge
