#!/bin/bash

# Grafana Configuration Script for ERP Integration Monitoring
echo "=== Setting up Grafana Monitoring for ERP Integration ==="
echo ""

GRAFANA_URL="http://localhost:3000"
PROMETHEUS_URL="http://prometheus:9090"
ADMIN_USER="admin"
ADMIN_PASS="admin"

echo "🔧 Grafana Setup Instructions:"
echo ""
echo "1. Access Grafana Dashboard:"
echo "   URL: $GRAFANA_URL"
echo "   Username: $ADMIN_USER"
echo "   Password: $ADMIN_PASS (default, change on first login)"
echo ""

echo "2. Add Prometheus Data Source:"
echo "   - Go to Configuration > Data Sources"
echo "   - Click 'Add data source'"
echo "   - Select 'Prometheus'"
echo "   - URL: $PROMETHEUS_URL"
echo "   - Click 'Save & Test'"
echo ""

echo "3. Import Integration Dashboard:"
echo "   - Go to '+' > Import"
echo "   - Upload: grafana-dashboard.json"
echo "   - Or copy/paste the JSON content"
echo "   - Select Prometheus data source"
echo "   - Click 'Import'"
echo ""

echo "4. Key Metrics to Monitor:"
echo "   ✓ Service Health Status"
echo "   ✓ Employee/Payroll/Accounting Sync Rates"
echo "   ✓ Error Rates by Type"
echo "   ✓ Response Time Distribution"
echo "   ✓ Database Connection Pool Status"
echo "   ✓ Sync Operations Timeline"
echo ""

echo "5. Alert Configuration (Optional):"
echo "   - Set up alerts for sync failures"
echo "   - Monitor service downtime"
echo "   - Track error rate thresholds"
echo ""

echo "🚀 Quick Test Commands:"
echo ""
echo "# Test Prometheus metrics endpoint:"
echo "curl http://localhost:8083/integration/actuator/prometheus"
echo ""
echo "# Check Prometheus targets:"
echo "curl http://localhost:9090/api/v1/targets"
echo ""
echo "# Trigger test sync for metrics:"
echo "curl -X POST -H 'Authorization: Basic YWRtaW46YWRtaW4xMjM=' \\"
echo "     http://localhost:8083/integration/camel/employee/sync"
echo ""

echo "📊 Available Dashboards:"
echo "   - ERP Integration Service Overview"
echo "   - Sync Performance Metrics"
echo "   - Error Monitoring & Alerting"
echo "   - System Health & Resources"
echo ""

echo "🔗 Access Links:"
echo "   Grafana: http://localhost:3000"
echo "   Prometheus: http://localhost:9090"
echo "   Integration API: http://localhost:8083/integration"
echo "   RabbitMQ Management: http://localhost:15672"
echo ""

echo "✅ Setup complete! Access Grafana and follow the steps above."