# OAuth2 Authorization Server Configuration
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          asoath:
            registration:
              client-id: asoath
              client-secret: '{bcrypt}EVqt3QnbUvstmduJ8XUkhfEAr1iqfM6pJWxO1ND/zNk='
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
              authorization-grant-types:
                - authorization_code
                - refresh_token
                - client_credentials
              redirect-uris:
                - https://erp-integration.yourcompany.com/login/oauth2/code/asoath
                - http://localhost:8083/login/oauth2/code/asoath
              scopes:
                - read
                - write
                - erp:access
            require-authorization-consent: false
            
        jwk:
          source: classpath:keys/jwt-private-pkcs8.pem
          
        settings:
          issuer: https://erp-integration.yourcompany.com
          authorization-endpoint: /oauth2/authorize
          token-endpoint: /oauth2/token
          jwk-set-endpoint: /oauth2/jwks
          revocation-endpoint: /oauth2/revoke
          introspection-endpoint: /oauth2/introspect
          userinfo-endpoint: /oauth2/userinfo
